on:
  workflow_dispatch

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: hub.docker.com
          repository: iodide/pyodide
          tag_with_ref: true
